export const toolbox = [
    {
        section: "Front End",
        tools: [
            { id: 1, tool: "React" },
            { id: 2, tool: "React Router Framework" },
            { id: 3, tool: "JavaScript" },
            { id: 4, tool: "HTML5" },
            { id: 5, tool: "CSS3" },
            { id: 6, tool: "Tailwind CSS" },
            { id: 7, tool: "Responsive Design" },
            { id: 8, tool: "Accessibility (a11y)" },
            { id: 9, tool: "Fetch API" },
            { id: 10, tool: "Async/Await" },
        ],
    },
    {
        section: "Back End",
        tools: [
            { id: 11, tool: "Node.js" },
            { id: 12, tool: "Express" },
            { id: 13, tool: "RESTful APIs" },
            { id: 14, tool: "PostgreSQL" },
            { id: 15, tool: "Prisma ORM" },
            { id: 16, tool: "JWT Auth" },
            { id: 17, tool: "Passport.js" },
            { id: 18, tool: "Bcrypt.js" },
        ],
    },
    {
        section: "Front End Tooling & Libraries",
        tools: [
            { id: 19, tool: "LocalStorage" },
            { id: 20, tool: "Vite" },
            { id: 21, tool: "Webpack & Babel" },
            { id: 22, tool: "Jest & Vitest" },
            { id: 23, tool: "React Testing Library" },
            { id: 24, tool: "TinyMCE Editor" },
            { id: 25, tool: "Vercel" },
        ],
    },
    {
        section: "Back End Tooling & Libraries",
        tools: [
            { id: 26, tool: "Multer" },
            { id: 27, tool: "Cloudinary" },
            { id: 28, tool: "EJS Templating" },
            { id: 29, tool: "express-validator" },
            { id: 30, tool: "DOMPurify & JSDOM" },
            { id: 31, tool: "MVC Pattern" },
            { id: 32, tool: "Error Handling" },
            { id: 33, tool: "dotenv" },
            { id: 34, tool: "Railway" },
        ],
    },
];
