const toolbox = [
    {
        section: "Front End",
        tools: [
            { id: 1, tool: "React" },
            { id: 2, tool: "React Router" },
            { id: 3, tool: "JavaScript" },
            { id: 4, tool: "HTML" },
            { id: 5, tool: "CSS" },
            { id: 6, tool: "DOM Manipulation" },
            { id: 7, tool: "Responsive Design (Flexbox, Grid, Media Queries)" },
            { id: 8, tool: "Accessibility (a11y)" },
            { id: 9, tool: "LocalStorage" },
            { id: 10, tool: "Modular Programming" },
            { id: 11, tool: "Asynchronous JS (Promises, async/await)" },
            { id: 12, tool: "Fetch API" },
            { id: 13, tool: "Data Structures & Algorithms" },
            { id: 14, tool: "Testing (Jest, Vitest, React Testing Library)" },
            { id: 15, tool: "Git & GitHub" },
            { id: 16, tool: "Build Tools (Vite, Webpack, Babel)" },
            { id: 17, tool: "Deployment (Vercel)" },
            { id: 18, tool: "Forms & File Handling" },
            { id: 19, tool: "EJS Partials" },
        ],
    },
    {
        section: "Back End",
        tools: [
            { id: 20, tool: "Node.js" },
            { id: 21, tool: "Express" },
            { id: 22, tool: "PostgreSQL" },
            { id: 23, tool: "SQL" },
            { id: 24, tool: "Prisma ORM" },
            { id: 25, tool: "Multer (File Uploads)" },
            { id: 26, tool: "Cloudinary (File Storage)" },
            { id: 27, tool: "EJS (Templating Engine)" },
            { id: 28, tool: "express-validator" },
            { id: 29, tool: "Sessions & Authentication" },
            { id: 30, tool: "Passport.js" },
            { id: 31, tool: "Bcrypt.js (Password Hashing)" },
            { id: 32, tool: "Recursion" },
            { id: 33, tool: "Private & Shared Access (Tokens, Links)" },
            { id: 34, tool: "Database Relationships (User-Folder-File)" },
            { id: 35, tool: "Server-side Error Handling" },
            { id: 36, tool: "Environment Variables & Security (dotenv)" },
            { id: 37, tool: "Deployment (Railway - Server & DB)" },
            { id: 38, tool: "Model-View-Controller (MVC) Architecture" },
        ],
    },
];

export { toolbox };
